<a href="https://colab.research.google.com/github/adong-hood/cs200/blob/main/assignment9_ch83_87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Chapter 8 UN Speech

This notebook contains selected sections of 8.3, 8.4, 8.5 and 8.7 from chapter 8. It requires the 'un-general-debates.csv' and 'country_codes.csv' datasets. You may download and upload the datasets from <a href = "http://pluto.hood.edu/~dong/datasets/">this link </a> if the reading is too slow. <font color = "red">Please refer to both the Runestone book and this notebook. </font>

In [ ]:
import string  #used for string methods
import pandas as pd
import numpy as np
from collections import Counter  #- count how many times items appear in a list, string, or other iterable.

In [ ]:
import nltk #-the Natural Language Toolkit (NLTK) library
nltk.download('punkt') #- core sentence tokenizer
nltk.download('punkt_tab') #-supporting data for that tokenizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
sw = set(stopwords.words('english'))
len(sw)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

198

In [ ]:
# sum treats True as 1 and False as 0, so adding up these booleans will give us the total number that True values.
# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', None, 'David'], 'Age': [25, None, 30, 22]}
df = pd.DataFrame(data)
df
# # Check for number of NA values in Name.
sum(df['Age'].isna())
# #- check who have na age.
df[df.Age.isna()].Name

# #-
data = {'Name': ['Alice', 'Bob', 'Abby', 'David'], 'Age': [25, None, 30, 22]}
df = pd.DataFrame(data)
df
sum(df.Name.str.startswith('A'))
# #- check unique name value
len(df.Name.unique())

4

In [ ]:
words = ["apple", "banana", "apple", "orange", "banana", "apple"]
counts = Counter(words)
counts

Counter({'apple': 3, 'banana': 2, 'orange': 1})

In [ ]:
#undf = pd.read_csv('http://pluto.hood.edu/~dong/datasets/un-general-debates.csv')
undf = pd.read_csv('/content/drive/MyDrive/cs200/datasets/un-general-debates.csv')
undf.head(3)

   session  year country                                               text
0       44  1989     MDV  ﻿It is indeed a pleasure for me and the member...
1       44  1989     FIN  ﻿\nMay I begin by congratulating you. Sir, on ...
2       44  1989     NER  ﻿\nMr. President, it is a particular pleasure ...

In [ ]:
c_codes = pd.read_csv('http://pluto.hood.edu/~dong/datasets/country_codes.csv', encoding='iso-8859-1')
c_codes.head(2)

,country,code_2,code_3,country_code,iso_3166_2,continent,sub_region,region_code,sub_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,142.0,34.0
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,150.0,154.0

# 8.5. Working with Text

### Exercise 4 (Q1 from 8.5):

With undf, **how many rows** from the United Nations dataset have a country code that starts with ‘M’?

Hint: use `str.startswith()` and count the total rows with `sum()`

In [ ]:
#

663

### Exercise 5 (Q2 from 8.5):  

With undf, **how many country codes** from the United Nations dataset have a country code that starts with ‘M’?

Notice how this is different from the last question. As each row of our dataset is a speech, the answer from last question was the number of speeches delivered by M countries (not unique), not the number of M countries (unique).

Hint: use `unique()` to find the unique country codes

In [ ]:
#

18

# 8.3 Merging and Tiding Data
<font color = "green">Read the beginning of Section 8.3 of the Runestone book carefully to merge the two dataframes above before answering the following questions.</font>

#### 8.3.1 Why perform the step below?

Your answer:

In [ ]:

undf.columns = ['session', 'year', 'code_3', 'text']

#### 8.3.2. What is the output of the code cell below? and Why?
Your answer:

In [ ]:
undfe = undf.merge(c_codes[['code_3', 'country', 'continent', 'sub_region']], how = 'outer')
undfe[undfe.code_3 == 'EU']

,session,year,code_3,text,country,continent,sub_region
2268,68.0,2013.0,EU,A year ago \nwhen we met in the General Assemb...,NaN,NaN,NaN
2269,67.0,2012.0,EU,﻿The advance of democracy has taken place in\n...,NaN,NaN,NaN
2270,69.0,2014.0,EU,The world today is much more dangerous than \n...,NaN,NaN,NaN
2271,66.0,2011.0,EU,Europe presents to you a message of \ncooperat...,NaN,NaN,NaN
2272,70.0,2015.0,EU,I am here today to reassure the General Assemb...,NaN,NaN,NaN

### Exercise 1:  
With undfe, how many countries has the `nan` value for its country name? What are the values of `code_3` of these countries? Hint: use isna() to check for NA values.

101

In [ ]:
#-code_3

array(['CSK', 'DDR', 'EU', 'YDYE', 'YUG'], dtype=object)

So the above codes don't match to country names.
* YDYE was the code for South Yemen, a country that existed from 1967 to 1990.
* CSK was the code for Czechoslovakia, which existed from 1918 to 1993 when it dissolved into the Czech Republic and Slovakia.
* YUG was the code for Yugoslavia, which existed from 1918 to 1992.
* DDR was East Germany, before the reunification of Germany after the fall of the Berlin Wall.
* We know that EU is the European Union.

We can fill these in "by hand."

In [ ]:
#- EU is done for you. Please do the other four code_3 values: 'CSK', 'DDR', 'YDYE', 'YUG'.
undfe.loc[undfe.code_3 == 'EU', 'country'] = 'European Union'
undfe[undfe.code_3 == 'EU']
#- fill in code.
# Add country names for unmatched country codes
missing_code = list(undfe[undfe.country.isna()].code_3.unique())
missing_country = ['South Yemen', 'Czechoslovakia', 'Yugoslavia', 'East Germany']

for i in range(len(missing_country)):
    undfe.loc[undfe.code_3 == missing_code[i], 'country'] = missing_country[i]

In [ ]:
#- No na anymore.
undfe[undfe['code_3'].isna()]

Empty DataFrame
Columns: [session, year, code_3, text, country, continent, sub_region]
Index: []

# 8.4. Most and Least Common Words

<font color ="green">Read the beginning of Section 8.4 of the Runestone book carefully before answering the following questions.</font>

Now we want to clean up the text so that we can analyze the most and least common words in the speeches. To do that, we need to complete the following four steps:

1. Convert all text to lower case.
2. Remove all punctuation.
3. Break the string into a list of words - tokenize
4. Remove stop words from the list.

We'll start by doing this just for the speeches from 1970 so we can work on smaller text.

#### 8.4.1 What does this step do?
Your answer:

In [ ]:
speeches_1970 = undfe[undfe.year == 1970].copy()
len(speeches_1970)

70

#### 8.4.2 What does this step do?
Your answer:

In [ ]:
speeches_1970['text'] = speeches_1970.text.apply(lambda x: x.lower())

#### 8.4.3. Explain the code below. Be as specific as possible.
Your answer:

In [ ]:
#- str.maketrans creates a translation table
speeches_1970['text'] = speeches_1970.text.apply(
    lambda x: x.translate(str.maketrans(string.punctuation, ' '*len(string.punctuation))))

#### 8.4.4. What does the code below do?
Your answer:

In [ ]:
speeches_1970['word_list'] = speeches_1970.text.apply(nltk.word_tokenize)
c = Counter(speeches_1970.word_list.sum())
c.most_common(10)

[('the', 25077),
 ('of', 16265),
 ('and', 9224),
 ('to', 9134),
 ('in', 6668),
 ('a', 4530),
 ('that', 3919),
 ('is', 3322),
 ('for', 2563),
 ('which', 2471)]

This is maybe not as interesting as we'd hoped. While these are common words, they don't tell us at all what the common themes were of the UN speeches. These words would be the most common for almost any text in english. Removing stopwords, that is common words like 'the', will let us get a more interesting list of the most common words.

#### 8.4.5 What does the code below do?
Your answer:

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
sw = set(stopwords.words('english'))
len(sw)
sw.add('’')
len(sw)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

199

#### Explain the code below. Why is it necessary?
Your answer:

In [ ]:
# We'll replace the word list with a new one after applying a function
speeches_1970['word_list'] = speeches_1970.word_list.apply(lambda list_of_words: [word for word in list_of_words if word not in sw])

c = Counter(speeches_1970.word_list.sum())
c.most_common(10)

Redo the analysis for 2015. Make sure the most common words do not contain any non-text charactors and they are interesting words, e.g. not including words such as 'must' or 'also'.

### Exercise 2:
Apply a lambda function on the `text` column to change the speech text to the lower case.

In [ ]:
#

### Exercise 3

Find out the most common and least common words in 2015 UN speeches. Make sure the most common words do not contain any non-text characters and they are interesting words, e.g. not including words such as 'must' or 'also'.

In [ ]:
#

# 8.7. Sentiment Analysis of UN Speeches¶

The Natural Language ToolKit (NLTK) provides us with many tools for sentiment analysis, e.g., [VADER (Valence Aware Dictionary and sEntiment Reasoner, not Darth Vader)](https://www.nltk.org/_modules/nltk/sentiment/vader.html). VADER performs better on normal text and does not require us to manually train a model.

In [ ]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [ ]:
from nltk import tokenize
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [ ]:

score = analyzer.polarity_scores("I love sci-fi movies!") #- Full sentence score
score

{'neg': 0.0, 'neu': 0.308, 'pos': 0.692, 'compound': 0.6696}

In [ ]:
# Our sentence
sentence = "I love sci-fi movies!"
# Split sentence into words (simplest tokenization)
words = sentence.split()
# Compute individual word scores
word_scores = [analyzer.polarity_scores(word)['compound'] for word in words]
# Compute average of word compound scores, less acurate.
average_score = sum(word_scores) / len(word_scores)
print(average_score)

0.159225

In [ ]:
score = analyzer.polarity_scores("I wouldn't suggest this solution to anyone.") #- Full sentence score
score

{'neg': 0.0, 'neu': 0.656, 'pos': 0.344, 'compound': 0.3869}

#### 8.7.1 What does this function do? Be as specific possible.
Your answer:

In [ ]:
def score_text(text):
  try:
    sentence_list = tokenize.sent_tokenize(text)
    cscore = 0.0
    for sent in sentence_list:
        ss = analyzer.polarity_scores(sent)['compound']
        cscore += ss
    return cscore / len(sentence_list)
  except:
    return np.nan

#### 8.7.2 Add compound score (sentiment score) to each speech by applying the above function.

In [ ]:
undfe.head(1)

   session  year code_3 text country continent sub_region
0      NaN   NaN    ABW  NaN   Aruba  Americas  Caribbean

In [ ]:
#- your answer

### Exercise 6.
Which countries are the most positive in their speeches throughout the years?

In [ ]:
#

### Exercise 7.
Which subregion is the most positive in their speeches throughout the years?

In [ ]:
#