<a href="https://colab.research.google.com/github/adong-hood/cs200/blob/main/assignment12_ethicsandlegal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Finding the Cheaters (7.3)

<p>Requires 'puzzle_anon.csv' and 'puzzle_real.csv' files. Pleae refer to 7.3 of the Runestone book. It may help to read this <a href =" https://github.com/BuzzFeedNews/2016-01-tennis-betting-analysis/blob/master/README.md"> README.md</a> for methodology used.</p>
<p>This notebook serves as a scratch pad. Check your answers on the Runestone site.</p>

In [2]:
import pandas as pd

### Step 1: Blind detection
You will have to design a strategy for identifying cheaters, such as lots of “high-movement” matches, high average difference between 'start odds'and 'end odds', etc.

#### Q-1: Find the ids of top five cheaters here.

In [3]:
odds = pd.read_csv('http://pluto.hood.edu/~dong/datasets/puzzle_anon.csv')
print(odds.shape)
odds.head() # each row represents one match. A player may have multiple matches.

(175, 3)

                  name  start odds  end odds
0  1718561694846000000    0.924528  0.154088
1  1693568023468290000    0.104886  0.104886
2  6228119144908420000    0.845956  0.140993
3  2416068425895370000    0.846787  0.141131
4  2416068425895370000    0.583809  0.145952

To find the cheaters, we'd like to identify those players that have a big difference between their starting odds and ending odds.

### Step 2: Reveal identities

But keep in mind we're not looking for the games where cheating was most likely to occur, we're looking for the players who cheated. Now we'd like to match the player names to their annonimized codes.

In [4]:
player_names = pd.read_csv('http://pluto.hood.edu/~dong/datasets/puzzle_real.csv')
print(player_names.shape)
player_names.head()

(149, 3)

    name  start odds  end odds
0   hill    0.501586  0.501586
1    bob    0.337860  0.056310
2   john    0.013989  0.002331
3  sally    0.530880  0.088480
4    bob    0.323761  0.064752

<p>We have the games played by players. We need to match this to the annonymous data in Step 1. The matching can be based on start odds and end odds of each match. </p>

Q-2: Find the names of top five cheaters here.

## Part 2: Ten simple rules for responsible big data research

Choose **two** of the ten rules and briefly explain each in your own words. Then, for each rule, give a simple example of what could go wrong if the rule is ignored in real-world big data research.

Finish with 1–2 sentences answering:
What is the most important idea about “responsible” data science you learned from this paper?

Your answer should be about 200-250 words. [<a href ="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005399">Paper link</a>]