<a href="https://colab.research.google.com/github/adong-hood/cs200/blob/main/midterm_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Midterm Project

<p>These topics have been covered so far:</p>
<ul>
<li>We have reviewed Python in Chapter 4. </li>
<li>In Chapter 5, we were introduced to Pandas and its common data structures (DataFrames and Series) and their many operations.</li>
<li> In Chapter 6, we covered exploratory data analysis, including EDA basics, visualization and graphing data on a map using web API, and web scraping. </li>
</ul>
<p>For the midterm project, you will apply what you have learned so far with happiness data. The datasets needed can found from <a href = "http://pluto.hood.edu/~dong/datasets/">this link</a>.</p>

**Please do not manually look for answers even if you can.**
<p>We start with some standard imports:</p>

In [2]:
import pandas as pd
import numpy as np

In [27]:
happiness_df = pd.read_csv('http://pluto.hood.edu/~dong/datasets/happiness_2017.csv').dropna(axis=1, how='all')
world_pop_df = pd.read_csv('http://pluto.hood.edu/~dong/datasets/world_countries.csv').dropna(axis=1, how='all')

## Exploring the basics

Do an `initial investigation` of the dataset. This process may include cleaning the data, and preparing it for data analysis.

**You can find some expected outputs for Q1-Q3 from Runestone book, Section 2.2.3, Q-5, Q-6, Q-12 and Section 2.3.1, Q-2 and Q-5.**

### Q-1: Calculating the average, standard deviation, maximum, mininum, median of happiness scores.  (10 points)
Your solution should only show these statistics for happiness scores.

### Q-2: What is the name and happiness score of the country with the lowest confidence in their national government? (10 points)

### Q-3 How many countries are in Western Europe and how many countries in Sub-Saharan Africa? (10 points)

### Q-4 What is the happiest country in East Asia? (10 points)

## Merging data

### Preprocesing Step (10 points)

To extract populations from world_pop_df, we have to merge happiness_df with world_pop_df. However, some of the country names in <code>world_counties.csv</code> and <code>happiness_2007.xlsx</code>do not match. We do want to extract populations of all countries. So there are data preprocessing steps needed.

There are 4 kinds of merge: 'inner', 'outer', 'left', and 'right'. We practiced inner merge previously.  To keep all countries in happiness_df when we merge happiness_df with world_pop_df, you should use left merge. You may find examples from https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html.

In [28]:
# You have to merge happiness_df and world_pop_df to get the population for each country in happiness_df. Pay attention to what kind of merge (left, right, outer) to use.
# Assume the merge is successful; you should have 140 rows and 34 columns after merging. Use merged_df for the merged data frame.

(140, 34)

Index(['Country', 'Region_x', 'Rank', 'HappinessScore', 'Life Ladder',
       'Log GDP per capita', 'Social support',
       'Healthy life expectancy at birth', 'Freedom to make life choices',
       'Generosity', 'Perceptions of corruption', 'Positive affect',
       'Negative affect', 'Confidence in national government', 'Code',
       'Region_y', 'Population', 'Area', 'Pop. Density', 'Coastline',
       'Net migration', 'Infant mortality', 'GDP', 'Literacy', 'Phones',
       'Arable', 'Crops', 'Other', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

Let's check out which countries do not have population data after merge.

In [29]:
merged_df[merged_df['Population'].isnull()][['Country','Population']]

                      Country  Population
12              United States         NaN
17             United Kingdom         NaN
31   Taiwan Province of China         NaN
35        Trinidad and Tobago         NaN
51                South Korea         NaN
64    Hong Kong S.A.R., China         NaN
71                     Kosovo         NaN
75                 Montenegro         NaN
82     Bosnia and Herzegovina         NaN
93    Palestinian Territories         NaN
114       Congo (Brazzaville)         NaN
116          Congo (Kinshasa)         NaN
118               Ivory Coast         NaN
134               South Sudan         NaN

These entries with <code>NaN</code> for Populatin column are due to **mismatch country names** in the two dataframes/file or **simply no population data**.The most difficult part is to resolve these `NaN` entries. For your convenience, you may use <a href = "http://pluto.hood.edu/~dong/datasets/country_mismatch_missing.txt"> country_mismatch_missing.txt </a> for mismatch country information. The goal to find extract all population data from the world_pop_df.

Below is an example, showing how to address mismatched country names.

In [ ]:
#- Check out what is used for the united states in the world population dataframe (world_pop_df)-> United States of America
print(world_pop_df[world_pop_df['Country'].str.contains("United States")])
#- Check out what is used for the united states in the  happiness dataframe (happiness_df)-> United States
print(happiness_df[happiness_df['Country'].str.contains("United States")])
#- Change 'United States of America' in the world_pop_df dataframe to match 'United States' in happiness_df.
world_pop_df.loc[world_pop_df['Country'].str.contains("United States"), 'Country'] = "United States"

You still need to take care of all the rest.

In [ ]:
#- fill in code for addressing other mixed-matched countries.

 **Merge happiness_df with world_pop_df again after cleaning. Name this one as merged_cleaned_df**.

In [32]:
merged_cleaned_df = # fill in code/implementation to merge again.
# check again.
merged_cleaned_df[merged_cleaned_df['Population'].isnull()][['Country','Population']]

                     Country  Population
71                    Kosovo         NaN
75                Montenegro         NaN
93   Palestinian Territories         NaN
134              South Sudan         NaN

You should see there are still **four** countries with no population data since these countries do not appear in the world_pop_df or world_countries file. We will set their population data to zero.

In [33]:
# you have four countries with NaN.
merged_cleaned_df['Population'] = merged_cleaned_df['Population'].fillna(0)
merged_cleaned_df[merged_cleaned_df['Population'].isnull()][['Country','Population']]

Empty DataFrame
Columns: [Country, Population]
Index: []

There should be no countries with NaN values for population. Finally, we are ready to use the merged dataframe.

**You may find the expected answers to Q-4 and Q-5 from the Runestone book, section 2.3, Q-8 and Q-9.**

### Q-5. Which country  has the largest population in Latin America and Caribbean. (10 points)

### Q-6. Find the average population of East Asia. (10 points)

## Web API: Graphing the Happiness Scores (20 points)

Graphing the happiness score of each country on the map. This should be very similar to what did in the Runestone book, Section 6.3.

Provide all the code needed for graphing the happiness score of each country on a world map.

The cleaning and import are done for you.

In [34]:
from altair import Chart, X, Y, Color, Scale
import altair as alt
from vega_datasets import data
import requests

In [ ]:
# We need 3-letter country code for each country in order to extract its
# numeric country codes via web API for graphing the map.
print(len(merged_cleaned_df[merged_cleaned_df.Code.isnull()]))
# This time  we remove countries with NaN for Code, i.e. no 3-letter country code.
merged_cleaned_df = merged_cleaned_df[merged_cleaned_df.Code.notnull()]
print(len(merged_cleaned_df[merged_cleaned_df.Code.isnull()])) # this should return 0.
merged_cleaned_df.shape  #- 136 rows

In [47]:
#- fill in your solution.

alt.Chart(...)

## Q-7. What role does the economy play in determining a country's happiness? And Why?(10 points)

 ### Q-8. What are the top three factors that contribute to a country's happiness? And why? (extra points: 10)